import { FAQItem } from "./types";

export const faqItems: FAQItem[] = [
  { id: "faq-1", category: "booking", categoryLabel: { fr: "Réservation", en: "Booking" }, question: { fr: "Comment puis-je réserver un chauffeur privé ?", en: "How can I book a private chauffeur?" }, answer: { fr: "Vous pouvez réserver via notre site web en cliquant sur « Réserver », par WhatsApp, par e-mail ou par téléphone. Nous recommandons de réserver au moins 24h à l'avance.", en: "You can book through our website by clicking 'Book Now', via WhatsApp, email or phone. We recommend booking at least 24 hours in advance." } },
  { id: "faq-2", category: "booking", categoryLabel: { fr: "Réservation", en: "Booking" }, question: { fr: "Puis-je réserver pour quelqu'un d'autre ?", en: "Can I book for someone else?" }, answer: { fr: "Oui, absolument. Il suffit de nous fournir le nom et le numéro de téléphone du passager lors de la réservation.", en: "Yes, absolutely. Simply provide us with the passenger's name and phone number when booking." } },
  { id: "faq-3", category: "booking", categoryLabel: { fr: "Réservation", en: "Booking" }, question: { fr: "Quelle est votre politique d'annulation ?", en: "What is your cancellation policy?" }, answer: { fr: "Les annulations sont gratuites jusqu'à 6 heures avant le trajet. Au-delà, des frais d'annulation de 50% peuvent s'appliquer.", en: "Cancellations are free up to 6 hours before the trip. After that, cancellation fees of 50% may apply." } },
  { id: "faq-4", category: "booking", categoryLabel: { fr: "Réservation", en: "Booking" }, question: { fr: "Puis-je modifier ma réservation ?", en: "Can I modify my booking?" }, answer: { fr: "Oui, vous pouvez modifier votre réservation gratuitement jusqu'à 4 heures avant le trajet.", en: "Yes, you can modify your booking free of charge up to 4 hours before the trip." } },
  { id: "faq-5", category: "pricing", categoryLabel: { fr: "Tarifs", en: "Pricing" }, question: { fr: "Comment sont calculés vos tarifs ?", en: "How are your prices calculated?" }, answer: { fr: "Nos tarifs sont fixes et basés sur la distance. Pas de surprises ni de frais cachés. Le prix inclut le véhicule, le chauffeur, l'eau et les péages.", en: "Our prices are fixed and based on distance. No surprises or hidden fees. The price includes the vehicle, chauffeur, water and tolls." } },
  { id: "faq-6", category: "pricing", categoryLabel: { fr: "Tarifs", en: "Pricing" }, question: { fr: "Quels moyens de paiement acceptez-vous ?", en: "What payment methods do you accept?" }, answer: { fr: "Nous acceptons les cartes bancaires, les espèces, les virements bancaires et PayPal.", en: "We accept credit cards, cash, bank transfers and PayPal." } },
  { id: "faq-7", category: "pricing", categoryLabel: { fr: "Tarifs", en: "Pricing" }, question: { fr: "Y a-t-il des suppléments pour les trajets de nuit ?", en: "Are there surcharges for night trips?" }, answer: { fr: "Un supplément de 20% s'applique entre 22h00 et 6h00, ainsi que les dimanches et jours fériés.", en: "A 20% surcharge applies between 10:00 PM and 6:00 AM, as well as Sundays and public holidays." } },
  { id: "faq-8", category: "pricing", categoryLabel: { fr: "Tarifs", en: "Pricing" }, question: { fr: "Proposez-vous des tarifs entreprise ?", en: "Do you offer corporate rates?" }, answer: { fr: "Oui, nous proposons des forfaits entreprise avec facturation mensuelle et tarifs préférentiels.", en: "Yes, we offer corporate packages with monthly billing and preferential rates." } },
  { id: "faq-9", category: "airport", categoryLabel: { fr: "Aéroport", en: "Airport" }, question: { fr: "Mon vol est retardé, que se passe-t-il ?", en: "My flight is delayed, what happens?" }, answer: { fr: "Nous suivons votre vol en temps réel. En cas de retard, votre chauffeur ajuste son heure d'arrivée automatiquement, sans frais supplémentaires.", en: "We track your flight in real time. In case of delay, your chauffeur adjusts automatically, at no extra charge." } },
  { id: "faq-10", category: "airport", categoryLabel: { fr: "Aéroport", en: "Airport" }, question: { fr: "Où me retrouve mon chauffeur à l'aéroport ?", en: "Where does my chauffeur meet me at the airport?" }, answer: { fr: "Votre chauffeur vous attend en zone d'arrivée avec un panneau à votre nom et vous escorte jusqu'au véhicule.", en: "Your chauffeur waits in the arrival zone with a name board and escorts you to the vehicle." } },
  { id: "faq-11", category: "airport", categoryLabel: { fr: "Aéroport", en: "Airport" }, question: { fr: "Combien de temps d'attente est inclus à l'aéroport ?", en: "How much waiting time is included at the airport?" }, answer: { fr: "45 minutes d'attente sont incluses après l'atterrissage. Pour les gares, 15 minutes sont incluses.", en: "45 minutes of waiting time are included after landing. For train stations, 15 minutes are included." } },
  { id: "faq-12", category: "airport", categoryLabel: { fr: "Aéroport", en: "Airport" }, question: { fr: "Desservez-vous d'autres aéroports que Nice ?", en: "Do you serve airports other than Nice?" }, answer: { fr: "Oui, nous assurons des transferts depuis Nice, Cannes-Mandelieu, Monaco Héliport, Marseille et les aéroports italiens.", en: "Yes, we provide transfers from Nice, Cannes-Mandelieu, Monaco Heliport, Marseille and Italian airports." } },
  { id: "faq-13", category: "long-distance", categoryLabel: { fr: "Longue Distance", en: "Long Distance" }, question: { fr: "Faites-vous des trajets vers l'Italie ?", en: "Do you travel to Italy?" }, answer: { fr: "Oui, nous assurons des transferts vers San Remo, Gênes, Milan, Portofino et toute la Riviera italienne.", en: "Yes, we provide transfers to San Remo, Genoa, Milan, Portofino and the entire Italian Riviera." } },
  { id: "faq-14", category: "long-distance", categoryLabel: { fr: "Longue Distance", en: "Long Distance" }, question: { fr: "Pouvez-vous me conduire à Genève ou Marseille ?", en: "Can you drive me to Geneva or Marseille?" }, answer: { fr: "Absolument. Nous proposons des trajets longue distance vers Marseille, Genève, Lyon et toutes les grandes villes.", en: "Absolutely. We offer long-distance trips to Marseille, Geneva, Lyon and all major cities." } },
  { id: "faq-15", category: "long-distance", categoryLabel: { fr: "Longue Distance", en: "Long Distance" }, question: { fr: "Y a-t-il des pauses prévues sur les longs trajets ?", en: "Are breaks planned on long trips?" }, answer: { fr: "Oui, sur les trajets de plus de 2 heures, nous prévoyons une pause confort.", en: "Yes, on trips longer than 2 hours, we plan a comfort break." } },
  { id: "faq-16", category: "services", categoryLabel: { fr: "Services & Infos", en: "Services & Info" }, question: { fr: "Vos chauffeurs parlent-ils anglais ?", en: "Do your chauffeurs speak English?" }, answer: { fr: "Oui, tous nos chauffeurs sont bilingues français-anglais. Certains parlent aussi italien, arabe ou espagnol.", en: "Yes, all our chauffeurs are bilingual French-English. Some also speak Italian, Arabic or Spanish." } },
  { id: "faq-17", category: "services", categoryLabel: { fr: "Services & Infos", en: "Services & Info" }, question: { fr: "Proposez-vous des sièges enfants ?", en: "Do you provide child seats?" }, answer: { fr: "Oui, nous disposons de sièges bébé, sièges enfant et rehausseurs. Demandez-les lors de votre réservation.", en: "Yes, we have baby seats, child seats and booster seats. Request them when booking." } },
  { id: "faq-18", category: "services", categoryLabel: { fr: "Services & Infos", en: "Services & Info" }, question: { fr: "Les animaux de compagnie sont-ils acceptés ?", en: "Are pets allowed?" }, answer: { fr: "Oui, les animaux de compagnie sont les bienvenus. Prévenez-nous simplement à l'avance.", en: "Yes, pets are welcome. Simply let us know in advance." } },
  { id: "faq-19", category: "services", categoryLabel: { fr: "Services & Infos", en: "Services & Info" }, question: { fr: "Êtes-vous disponible 24h/24 ?", en: "Are you available 24/7?" }, answer: { fr: "Oui, notre service est disponible 24/7 y compris weekends et jours fériés.", en: "Yes, our service is available 24/7 including weekends and public holidays." } },
  { id: "faq-20", category: "services", categoryLabel: { fr: "Services & Infos", en: "Services & Info" }, question: { fr: "Y a-t-il le Wi-Fi dans les véhicules ?", en: "Is there Wi-Fi in the vehicles?" }, answer: { fr: "Oui, tous nos véhicules sont équipés du Wi-Fi gratuit, de chargeurs USB et de bouteilles d'eau fraîche.", en: "Yes, all vehicles have free Wi-Fi, USB chargers and fresh water bottles." } },
];
